### ISSUE TITLE
Não é possivel escolher o content type do arquivo que você está subindo.

### ISSUE THREAD

**Issue by petrious** [optsoldev/components-backend-core#95]
Eu percebi que quando você sobe um arquivo pelo uploadblob passando o stream ele salva o arquivo como application/octet-stream
dessa maneira não é possivel renderizar o arquivo pelo URL que ele gera. Caso você consiga tipar o arquivo para application/pdf que é o  caso ele renderiza normalmente.

**Comment by carlosmachel** [comment]
Boa tarde Petrious, posso adicionar para setar o content type do arquivo, mas pelo backend vc consegue definir qual o tipo quando vc faz o download. Vc estaria abrindo a URL direto do Frontend?

**Comment by petrious** [comment]
Isso eu estou abrindo a URL direto do frontEnd.
Não queria fazer o download...
